### ISSUE TITLE
将yaml中Category改为'NUMERIC'后报错

### ISSUE THREAD

**Issue by kevin-jfzhu** [kerlomz/captcha_trainer#58]
Traceback (most recent call last):
    sdk = muggle_ocr.SDK(model_type=muggle_ocr.ModelType.Captcha, conf_path='myyaml.yaml')
  File "/project_path/venv/lib/python3.7/site-packages/muggle_ocr/sdk.py", line 1036, in __init__
    self.predict(init_img)
  File "/project_path/venv/lib/python3.7/site-packages/muggle_ocr/sdk.py", line 1045, in predict
    result = self.interface.predict_batch(image_batch, None)
  File "/project_path/venv/lib/python3.7/site-packages/muggle_ocr/sdk.py", line 826, in predict_batch
    output_split
  File "/project_path/venv/lib/python3.7/site-packages/muggle_ocr/sdk.py", line 850, in predict_func
    expression += self.decode_maps(model.category)[i]
KeyError: 13

保持默认的ALPHANUMERIC可以正常执行

**Comment by kerlomz** [comment]
model_type和conf_path参数不得同时使用

**Comment by kevin-jfzhu** [comment]
Ok, thanks for the clarification
